<?php

/**
 * @file
 * Contains vtlaw_migrate.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function project_a_migrate_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the vtlaw_migrate module.
    case 'help.page.project_a_migrate':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom migration classes for PROJECT_A.') . '</p>';
      return $output;

    default:
  }
}
